/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "on-error": "#ffffff",
        "surface-container": "#eaedff",
        "on-primary-fixed-variant": "#004b74",
        "surface-bright": "#faf8ff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001d32",
        "on-primary": "#ffffff",
        "primary-fixed": "#cde5ff",
        "primary-container": "#0369a1",
        "outline": "#707881",
        "on-surface-variant": "#40474f",
        "primary-fixed-dim": "#94ccff",
        "surface-container-low": "#f2f3ff",
        "tertiary-fixed-dim": "#62df7d",
        "surface": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "secondary": "#006781",
        "background": "#faf8ff",
        "on-error-container": "#93000a",
        "tertiary": "#005923",
        "tertiary-fixed": "#7ffc97",
        "error-container": "#ffdad6",
        "primary": "#00507d",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#002109",
        "on-tertiary-container": "#7efb96",
        "tertiary-container": "#007431",
        "on-secondary-container": "#00647d",
        "secondary-fixed-dim": "#81d1f0",
        "on-secondary-fixed": "#001f29",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#dae2fd",
        "surface-tint": "#006399",
        "on-surface": "#131b2e",
        "on-primary-container": "#cbe4ff",
        "secondary-fixed": "#b9eaff",
        "inverse-primary": "#94ccff",
        "outline-variant": "#c0c7d1",
        "on-background": "#131b2e",
        "inverse-surface": "#283044",
        "on-tertiary-fixed-variant": "#005320",
        "surface-container-high": "#e2e7ff",
        "on-secondary-fixed-variant": "#004d62",
        "secondary-container": "#8fdfff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "1rem",
        "gutter": "1rem",
        "space-3xl": "3rem",
        "space-lg": "1rem",
        "gutter-desktop": "1.5rem",
        "space-2xl": "2rem",
        "space-xl": "1.5rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "margin-desktop": "2rem",
        "space-xs": "0.25rem",
        "margin-tablet": "1.5rem",
        "space-2xs": "0.125rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["IBM Plex Sans", "sans-serif"],
        "code": ["JetBrains Mono", "monospace"],
        "headline-sm": ["IBM Plex Sans", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "metric-lg": ["JetBrains Mono", "monospace"],
        "headline-md": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "display-mobile": ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
        "label-caps": ["IBM Plex Sans", "sans-serif"],
        "metric-sm": ["JetBrains Mono", "monospace"],
        "metric-md": ["JetBrains Mono", "monospace"],
        "display": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["22px", { "lineHeight": "30px", "fontWeight": "600" }],
        "code": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "metric-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "metric-sm": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "metric-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
